version: '3.8'

services:
  redis:
    container_name: redis_limiter
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  limiter:
    container_name: limiter
    build:
      context: .
      target: app
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - redis

  test:
    container_name: limiter_test
    build:
      context: .
      target: test
    env_file: .env
    depends_on:
      - redis

volumes:
  redis_data:
